name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@9b0aaba843baa48a459c1acb791f8aeefbfa37dd
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

          API_BASE_URL: ${{ secrets.WAKATIME_API_URL }}
          SHOW_TITLE: true
          BLOCKS: ░▒▓█
          CODE_LANG: rust
          TIME_RANGE: last_7_days
          LANG_COUNT: 10
          SHOW_TIME: true
          SHOW_TOTAL: true
          STOP_AT_OTHER: true
